#!/bin/bash

# getopts gets option command here either -c or -f"
while getopts "f:c:" opt; do
    case "$opt" in
    c) result=$(echo "scale=4; ($OPTARG * (9/5))+32" | bc) ;;
    f) result=$(echo "scale=2; ($OPTARG - 32 * (5/9))+32" | bc) ;;
    \?) echo "enter either Celsius option -c 20 or Farenheit -f 15" ;;
    esac
done

echo "$result"
